---
locale: es
tags: []
layout: input_bottom
editor: code
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
name: Tiempo al tiempo
