---
name: Práctica Funciones y Tipos de Datos
locale: es
type: practice
beta: false
teacher_info: ''
language: javascript
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 5
- 13
- 6
- 7
- 8
- 9
- 10
- 11
- 12
private: false
