---
locale: es
tags:
- booleanos
- funciones
- casos-borde
- reutilizacion
layout: input_right
editor: code
type: problem
extra_visible: true
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
name: "¿Me conviene?"
