---
locale: es
tags:
- strings
- alternativa-condicional
- concatenacion
- modificar-codigo
layout: input_right
editor: code
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
name: Más Cartelitos
