---
locale: es
tags: []
layout: input_right
editor: code
type: problem
extra_visible: true
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
name: "¡Quiero retruco!"
